-- Bulk Insert Databases for ServerId 5, ServerIndex 13

-- Ensure Server 5 exists (Optional safety check)
IF NOT EXISTS (SELECT 1 FROM ServerData WHERE ServerId = 5)
BEGIN
    PRINT 'Warning: ServerId 5 does not exist. Please create it first or the inserts will fail due to Foreign Key constraint.'
    -- SET IDENTITY_INSERT ServerData ON
    -- INSERT INTO ServerData (ServerId, ServerName, HostName, ServerIndex) VALUES (5, 'Indus Server (New)', 'INDUS-SQL-NEW', '13')
    -- SET IDENTITY_INSERT ServerData OFF
END

-- Temporary table to hold names for processing
CREATE TABLE #TempDatabases5 (DbName NVARCHAR(200))

INSERT INTO #TempDatabases5 (DbName) VALUES
-- Image 0
('Indas'),
('indus'),
('Indus_Accu'),
('Indus_Akar'),
('Indus_AKSA'),
('Indus_Amit'),
('Indus_Archana'),
('Indus_Arihant'),
('Indus_Atharva'),
('Indus_Boxzons'),
('Indus_Chandni'),
('Indus_Chhajed'),
('Indus_ColorGraphics'),
('INDUS_COLORS'),
('Indus_Continuity'),
('Indus_CopyShoppe'),
('Indus_Creative'),
('INDUS_CRM'),
('Indus_Dashboard'),
('Indus_Delux'),
('Indus_Demo'),
('Indus_DemoPP'),
('Indus_DesignIndia'),
('Indus_DesignIndia2'),
('Indus_Dev_Prints'),
('Indus_Dhalkot'),
('INDUS_DIVYA'),
('INDUS_DMI'),
('Indus_Dutta'),
('Indus_EB_Press'),
('Indus_Efex'),
('Indus_Employees'),
('Indus_Extreme'),
('Indus_FiveStar'),
-- Image 1
('Indus_Ganesh_Mudra'),
('Indus_Girnar'),
('Indus_Goenka'),
('Indus_GPH'),
('Indus_GraphicSystem'),
('Indus_HBD'),
('Indus_Hipac'),
('Indus_Huemen'),
('Indus_Images'),
('Indus_jaina'),
('Indus_Jayboxes'),
('Indus_Jhaveri'),
('Indus_JMPL'),
('Indus_Kalpavruksha'),
('Indus_Labanya'),
('Indus_Labelman'),
('Indus_MayurPack'),
('Indus_Meshprint'),
('Indus_Modal_International_Backup'),
('Indus_Moorthy'),
('Indus_MPAD_BKP'),
('Indus_MultiHitech'),
('INDUS_NAGEEN'),
('INDUS_NAGEEN_PRINTPACK'),
('Indus_Navratan'),
('Indus_Neminath'),
('Indus_Nine_Step'),
('Indus_NineSquare'),
('Indus_NS_PrintOPack'),
('Indus_Nukkad'),
('Indus_OK_Print'),
('Indus_Opal'),
('Indus_Oxford'),
-- Image 2
('Indus_Packaging_India'),
('Indus_Paras'),
('Indus_ParasWebcoat'),
('Indus_Payorite'),
('Indus_PearlPrintService'),
('Indus_PearlPrintService_Images'),
('Indus_Pixel'),
('Indus_Prem_Printing'),
('Indus_Prince'),
('Indus_Printing_Samachar'),
('Indus_Printol'),
('Indus_PrintVision'),
('Indus_Printwell'),
('Indus_Prishi'),
('INDUS_R_PAC'),
('Indus_Rak_Media'),
('Indus_Rangoli'),
('Indus_RTGraphics'),
('Indus_Sailmp'),
('Indus_Saroj'),
('Indus_Shell'),
('Indus_Sheth_Impression'),
('Indus_Sheth_Impression_XL'),
('Indus_ShreeCalender'),
('Indus_Shreedhar'),
('Indus_ShreeGanesh'),
('Indus_Shreenath'),
('Indus_SK_Offset'),
('Indus_SKE'),
('Indus_SKumar'), -- Note: 'In Recovery' status omitted
('Indus_Sriyug_Print'),
('Indus_Supriya'),
('Indus_Surbhi'),
-- Image 3 (Indus_Surbhi duplicate skipped)
('Indus_Swan'),
('Indus_Tanmay'),
('Indus_Testing'),
('Indus_Threeview'),
('Indus_TOG'),
('Indus_Traning'),
('Indus_Updak'),
('Indus_VYJACK'),
('Indus_YashPackers'),
('IndusDSS'),
('IndusEenterpriseAcme'), -- Typo in screenshot preserved
('IndusEnterprise2KMLabel'),
('IndusEnterpriseArab'),
('IndusEnterpriseAshish'),
('IndusEnterpriseContinutyDemo'),
('IndusEnterpriseDeep'),
('IndusEnterpriseDemo'),
('IndusEnterpriseDemoRitesh'),
('IndusEnterpriseDemoUnit'),
('IndusEnterpriseDemoVikram'),
('IndusEnterpriseDesignIndia'),
('IndusEnterpriseDesignprint'),
('IndusEnterpriseDurrant'),
('IndusEnterpriseDutta'),
('IndusEnterpriseEasternPrinting'),
('IndusEnterpriseEskaysScanna'),
('IndusEnterpriseFlexo'),
('IndusEnterpriseGoodluck'),
('IndusEnterpriseGoodluckBkp'),
('IndusEnterpriseGraphicprints'),
('IndusEnterpriseGujaratOffset'),
('IndusenterpriseHexachrome'),
('IndusEnterpriseHiraPrint'),
-- Image 4
('IndusEnterpriseImpression'),
('IndusEnterpriseInPrint'),
('IndusEnterpriseJaina'),
('IndusEnterpriseJaipurPrinters'),
('IndusEnterpriseJayBoxes'),
('IndusEnterpriseJoseph'),
('IndusEnterpriseKeyline'),
('IndusEnterpriseKreatica'),
('IndusEnterpriseKrishna'),
('IndusEnterpriseManali'),
('IndusEnterpriseMarks'),
('IndusEnterpriseMPAD'),
('IndusEnterpriseNageen'),
('IndusEnterpriseNewInstallation'),
('IndusEnterpriseNewInstallationPackaging'),
('IndusEnterpriseNineStep'),
('IndusEnterpriseOceans'),
('IndusEnterpriseOmegaPrintopack'),
('IndusEnterpriseOnlineprint'),
('IndusEnterpriseOrientLitho'),
('IndusEnterpriseOrientLithoBkp'),
('IndusEnterpriseOrientUniversal'),
('IndusEnterprisePackplay'),
('IndusEnterprisePBholotech'),
('IndusEnterprisePBholotechTesting'),
('IndusEnterprisePrintSmith'),
('IndusEnterpriseQuantum'),
('IndusEnterpriseQuarterfold'),
('IndusEnterpriseQuarterfoldTesting'),
('IndusEnterpriseRainbow'),
('IndusEnterpriseRajeshOffset'),
('IndusEnterpriseRangoliOffset'),
('IndusEnterpriseRashtrothana'),
('IndusEnterpriseRaskin'),
-- Additional Image
('IndusEnterpriseRep'),
('IndusEnterpriseReva'),
('IndusEnterpriseRK'),
('IndusEnterpriseRSGraphics'),
('IndusEnterpriseSaiSriLabels'),
('IndusEnterpriseSalasar'),
('IndusEnterpriseSaraswati'),
('IndusEnterpriseScanTrans'),
('IndusEnterpriseShell'),
('IndusEnterpriseShivganga'),
('IndusEnterpriseShreeCalendar'),
('IndusEnterpriseShreeKrishna'),
('IndusEnterpriseShreeSalasar'),
('IndusEnterpriseShriVaishnavi'),
('IndusEnterpriseShubham'),
('IndusEnterPriseSkumar'),
('IndusEnterpriseSrikriscon'),
('IndusEnterpriseSterling'),
('IndusEnterpriseSuraj'),
('IndusEnterpriseSwanpress'),
('IndusEnterpriseSwastik'),
('IndusEnterpriseSwetaPackaging'),
('IndusEnterpriseTaj'),
('IndusEnterpriseVamsiArt'),
('IndusEnterpriseViViInternational'),
('IndusEnterpriseWeePrint'),
('IndusEnterpriseWinways'),
('IndusOffice')

-- Insert into DatabaseDetail
INSERT INTO DatabaseDetail (DatabaseName, ServerId, ServerIndex, ClientName)
SELECT 
    DbName,
    5, -- ServerId
    '13', -- ServerIndex (as string)
    CASE 
        WHEN DbName LIKE 'IndusEnterprise%' THEN SUBSTRING(DbName, 16, LEN(DbName))
        WHEN DbName LIKE 'Indus_%' THEN SUBSTRING(DbName, 7, LEN(DbName))
        WHEN DbName LIKE 'Indus%' AND LEN(DbName) > 5 THEN SUBSTRING(DbName, 6, LEN(DbName)) -- Catch cases like IndusDSS -> DSS
        ELSE DbName 
    END
FROM #TempDatabases5
WHERE NOT EXISTS (SELECT 1 FROM DatabaseDetail WHERE DatabaseName = #TempDatabases5.DbName AND ServerId = 5)

-- Cleanup
DROP TABLE #TempDatabases5

PRINT 'Databases for Server 5 inserted successfully.'
SELECT * FROM DatabaseDetail WHERE ServerId = 5
