
import React, { useState, useEffect } from 'react';
import { api } from '../services/api';
import { Project } from '../types';
import { Plus, Search, MoreVertical, ExternalLink, Calendar, Trash2, Loader2 } from 'lucide-react';
import { Link } from 'react-router-dom';

const ProjectList: React.FC = () => {
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [saving, setSaving] = useState(false);
  const [newProject, setNewProject] = useState({
    clientName: '',
    description: '',
    startDate: '',
    endDate: ''
  });
  const [stats, setStats] = useState<Record<number, any>>({});

  const loadProjects = async () => {
    try {
      const data = await api.projects.getAll();
      setProjects(data);
    } catch (err) {
      console.error('Error loading projects:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadProjects();
  }, []);

  useEffect(() => {
    const loadStats = async () => {
      const newStats: Record<number, any> = {};
      await Promise.all(projects.map(async (p) => {
        try {
          const data = await api.projects.getDashboard(p.projectId);
          newStats[p.projectId] = data;
        } catch (e) {
          console.error(`Failed to load stats for project ${p.projectId}`, e);
        }
      }));
      setStats(newStats);
    };

    if (projects && projects.length > 0) {
      loadStats();
    }
  }, [projects]);

  const handleAdd = async () => {
    if (!newProject.clientName) {
      alert('Please enter a client name');
      return;
    }
    setSaving(true);
    try {
      const project: any = {
        // projectId is auto-generated by backend/DB for bigint
        clientName: newProject.clientName,
        description: newProject.description || '',
        status: 'Active',
        isActive: true
      };

      // Add dates if provided
      if (newProject.startDate) {
        project.startDate = newProject.startDate + 'T00:00:00Z'; // Add time component
      }
      if (newProject.endDate) {
        project.targetCompletionDate = newProject.endDate + 'T00:00:00Z';
      }


      console.log('Creating project with data:', JSON.stringify(project, null, 2));
      await api.projects.create(project);
      await loadProjects();
      setShowModal(false);
      setNewProject({ clientName: '', description: '', startDate: '', endDate: '' });
    } catch (err: any) {
      console.error('Full error:', err);
      const errorMessage = err.message || err.toString();
      alert(`Failed to create project: ${errorMessage}`);
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (id: number) => {
    if (confirm('Are you sure you want to delete this project and all its data?')) {
      try {
        await api.projects.delete(id);
        await loadProjects();
      } catch (err) {
        console.error('Error deleting project:', err);
        alert('Failed to delete project. Please try again.');
      }
    }
  };

  const filtered = projects.filter(p =>
    p.clientName.toLowerCase().includes(search.toLowerCase()) ||
    p.description.toLowerCase().includes(search.toLowerCase())
  );

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="flex flex-col items-center gap-4">
          <Loader2 className="w-8 h-8 animate-spin text-blue-600" />
          <p className="text-slate-500 dark:text-zinc-400">Loading projects...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold">Clients & Projects</h1>
          <p className="text-slate-500 dark:text-zinc-400 mt-1">Manage multiple migration environments.</p>
        </div>
        <button
          onClick={() => setShowModal(true)}
          className="inline-flex items-center gap-2 px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-all shadow-sm"
        >
          <Plus size={18} />
          New Client Project
        </button>
      </div>

      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
        <input
          type="text"
          placeholder="Search by client or project details..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="w-full pl-10 pr-4 py-3 bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-xl outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all shadow-sm"
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
        {filtered.map(project => (
          <div key={project.projectId} className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-2xl shadow-sm hover:shadow-md transition-all group overflow-hidden">
            <div className="p-6">
              <div className="flex items-start justify-between mb-4">
                <div className="w-12 h-12 rounded-xl bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 flex items-center justify-center font-bold text-xl">
                  {project.clientName[0]}
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handleDelete(project.projectId)}
                    className="p-2 text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/10 rounded-lg transition-colors"
                  >
                    <Trash2 size={16} />
                  </button>
                </div>
              </div>
              <h3 className="text-lg font-bold truncate">{project.clientName}</h3>
              <p className="text-slate-500 dark:text-zinc-400 text-sm mt-1 h-10 line-clamp-2">
                {project.description}
              </p>

              {/* Progress Stats */}
              <div className="mt-4 space-y-3">
                {/* Data Transfer Progress */}
                <div>
                  <div className="flex justify-between text-xs mb-1">
                    <span className="text-slate-500 dark:text-zinc-400">Data Transfer</span>
                    <span className="font-medium text-slate-700 dark:text-zinc-300">
                      {stats[project.projectId]?.transferProgress || 0}%
                    </span>
                  </div>
                  <div className="h-1.5 w-full bg-slate-100 dark:bg-zinc-800 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-blue-500 rounded-full transition-all duration-500"
                      style={{ width: `${stats[project.projectId]?.transferProgress || 0}%` }}
                    />
                  </div>
                </div>

                {/* Verification Progress */}
                <div>
                  <div className="flex justify-between text-xs mb-1">
                    <span className="text-slate-500 dark:text-zinc-400">Verification</span>
                    <span className="font-medium text-slate-700 dark:text-zinc-300">
                      {stats[project.projectId]?.verificationProgress || 0}%
                    </span>
                  </div>
                  <div className="h-1.5 w-full bg-slate-100 dark:bg-zinc-800 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-emerald-500 rounded-full transition-all duration-500"
                      style={{ width: `${stats[project.projectId]?.verificationProgress || 0}%` }}
                    />
                  </div>
                </div>
              </div>

              <div className="mt-6 flex items-center gap-4 text-xs font-medium text-slate-400 dark:text-zinc-500">
                <div className="flex items-center gap-1.5">
                  <Calendar size={14} />
                  {new Date(project.createdAt).toLocaleDateString()}
                </div>
              </div>
            </div>

            <div className="px-6 py-4 bg-slate-50 dark:bg-zinc-800/50 flex items-center justify-between border-t border-slate-100 dark:border-zinc-800">
              <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Active Migration</span>
              <Link
                to={`/projects/${project.projectId}`}
                className="inline-flex items-center gap-1.5 text-sm font-bold text-blue-600 hover:text-blue-700 transition-colors"
              >
                Open Project
                <ExternalLink size={14} />
              </Link>
            </div>
          </div>
        ))}
        {filtered.length === 0 && (
          <div className="col-span-full py-12 text-center bg-white dark:bg-zinc-900 border border-dashed border-slate-300 dark:border-zinc-800 rounded-2xl">
            <UsersIcon size={48} className="mx-auto text-slate-300 mb-4" />
            <h3 className="text-lg font-medium text-slate-900 dark:text-white">No projects found</h3>
            <p className="text-slate-500 dark:text-zinc-400">Try adjusting your search or create a new project.</p>
          </div>
        )}
      </div>

      {/* Add Modal */}
      {showModal && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-white dark:bg-zinc-900 w-full max-w-md rounded-2xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200">
            <div className="p-6 border-b border-slate-100 dark:border-zinc-800 flex items-center justify-between">
              <h2 className="text-xl font-bold">New Client Project</h2>
              <button onClick={() => setShowModal(false)} className="text-slate-400 hover:text-slate-600 dark:hover:text-white">
                <X size={20} />
              </button>
            </div>
            <div className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-semibold mb-1.5">Client Name</label>
                <input
                  type="text"
                  value={newProject.clientName}
                  onChange={(e) => setNewProject({ ...newProject, clientName: e.target.value })}
                  className="w-full px-4 py-2.5 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="e.g. Acme Industries"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1.5">Project Description</label>
                <textarea
                  value={newProject.description}
                  onChange={(e) => setNewProject({ ...newProject, description: e.target.value })}
                  className="w-full px-4 py-2.5 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl outline-none focus:ring-2 focus:ring-blue-500 min-h-[100px]"
                  placeholder="Summarize the migration scope..."
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold mb-1.5">Start Date</label>
                  <input
                    type="date"
                    value={newProject.startDate}
                    onChange={(e) => setNewProject({ ...newProject, startDate: e.target.value })}
                    className="w-full px-4 py-2.5 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-semibold mb-1.5">End Date</label>
                  <input
                    type="date"
                    value={newProject.endDate}
                    onChange={(e) => setNewProject({ ...newProject, endDate: e.target.value })}
                    className="w-full px-4 py-2.5 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>
              </div>
            </div>
            <div className="p-6 bg-slate-50 dark:bg-zinc-800/50 flex gap-3">
              <button
                onClick={() => setShowModal(false)}
                className="flex-1 py-2.5 bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-700 rounded-xl font-medium"
              >
                Cancel
              </button>
              <button
                onClick={handleAdd}
                disabled={saving}
                className="flex-1 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-bold transition-all shadow-lg shadow-blue-500/20 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {saving ? 'Creating...' : 'Create Project'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

const UsersIcon = ({ size, className }: { size: number, className?: string }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" /><circle cx="9" cy="7" r="4" /><path d="M22 21v-2a4 4 0 0 0-3-3.87" /><path d="M16 3.13a4 4 0 0 1 0 7.75" /></svg>
);
const X = ({ size }: { size: number }) => <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18" /><path d="m6 6 12 12" /></svg>;

export default ProjectList;
