
import React, { useState, useEffect, useMemo } from 'react';
import { useParams, Link } from 'react-router-dom';
import { api } from '../services/api';
import { DataTransferCheck, Status, ModuleMaster, WebTable } from '../types';
import { Plus, Search, Filter, Trash2, Edit3, Download, Check, Loader2, ArrowLeft } from 'lucide-react';

const TransferChecks: React.FC = () => {
  const { projectId: projectIdStr } = useParams<{ projectId: string }>();
  const projectId = projectIdStr ? parseInt(projectIdStr, 10) : 0;

  const [items, setItems] = useState<DataTransferCheck[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<Status | 'All'>('All');
  const [editingItem, setEditingItem] = useState<DataTransferCheck | null>(null);
  const [showModal, setShowModal] = useState(false);
  const [saving, setSaving] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState<{ show: boolean; id: number | null }>({ show: false, id: null });

  // Module Master State
  const [moduleMasters, setModuleMasters] = useState<ModuleMaster[]>([]);
  const [webTables, setWebTables] = useState<WebTable[]>([]);
  const [selectedModule, setSelectedModule] = useState<string>('');

  const loadItems = async () => {
    if (!projectId) return;
    try {
      const [data, modules, tables] = await Promise.all([
        api.dataTransfer.getByProject(projectId),
        api.moduleMaster.getAll(),
        api.webTables.getAll()
      ]);
      setItems(data);
      setModuleMasters(modules);
      setWebTables(tables);
    } catch (err) {
      console.error('Error loading data:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadItems();
  }, [projectId]);

  useEffect(() => {
    if (editingItem) {
      setSelectedModule(editingItem.moduleName);
    } else {
      setSelectedModule('');
    }
  }, [editingItem]);

  const uniqueModules = Array.from(new Set(moduleMasters.map(m => m.moduleName)));
  const availableSubModules = moduleMasters
    .filter(m => m.moduleName === selectedModule)
    .map(m => m.subModuleName);

  // Filter Web Tables based on selected Module's GroupIndex
  const availableTables = useMemo(() => {
    if (!selectedModule) return [];

    // Find the group index of the selected module (using the first match as module names should group together)
    const moduleInfo = moduleMasters.find(m => m.moduleName === selectedModule);
    if (!moduleInfo || moduleInfo.groupIndex === undefined) return [];

    return webTables.filter(t => t.groupIndex === moduleInfo.groupIndex);
  }, [selectedModule, moduleMasters, webTables]);

  const distinctDesktopTables = Array.from(new Set(availableTables.map(t => t.desktopTableName).filter(Boolean)));
  const distinctWebTables = Array.from(new Set(availableTables.map(t => t.tableName).filter(Boolean)));

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    try {
      const form = e.target as HTMLFormElement;
      const formData = new FormData(form);

      const itemData: DataTransferCheck = {
        transferId: editingItem?.transferId, // Undefined for new items
        projectId: projectId,
        moduleName: formData.get('moduleName') as string,
        subModuleName: formData.get('subModuleName') as string,
        condition: formData.get('condition') as string,
        tableNameDesktop: formData.get('tableNameDesktop') as string,
        tableNameWeb: formData.get('tableNameWeb') as string,
        recordCountDesktop: Number(formData.get('recordCountDesktop')) || 0,
        recordCountWeb: Number(formData.get('recordCountWeb')) || 0,
        status: formData.get('status') as Status,
        isCompleted: formData.get('status') === 'Completed',
        comments: formData.get('comments') as string
      };

      if (editingItem?.transferId) {
        await api.dataTransfer.update(editingItem.transferId, itemData);
      } else {
        await api.dataTransfer.create(itemData);
      }

      await loadItems();
      setShowModal(false);
      setEditingItem(null);
    } catch (err) {
      console.error('Error saving transfer check:', err);
      alert('Failed to save transfer check. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const handleSaveAs = async (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    setSaving(true);
    try {
      const button = e.currentTarget;
      const form = button.closest('form');
      if (!form) throw new Error('Form not found');

      const formData = new FormData(form);

      const newItem: DataTransferCheck = {
        // ID generated by backend
        projectId: projectId,
        moduleName: formData.get('moduleName') as string,
        subModuleName: formData.get('subModuleName') as string,
        condition: formData.get('condition') as string,
        tableNameDesktop: formData.get('tableNameDesktop') as string,
        tableNameWeb: formData.get('tableNameWeb') as string,
        recordCountDesktop: Number(formData.get('recordCountDesktop')) || 0,
        recordCountWeb: Number(formData.get('recordCountWeb')) || 0,
        status: formData.get('status') as Status,
        isCompleted: formData.get('status') === 'Completed',
        comments: formData.get('comments') as string
      };

      await api.dataTransfer.create(newItem);
      await loadItems();
      setShowModal(false);
      setEditingItem(null);
    } catch (err) {
      console.error('Error saving as new transfer check:', err);
      alert('Failed to save as new record. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = (id: number) => {
    setDeleteConfirm({ show: true, id });
  };

  const confirmDelete = async () => {
    if (!deleteConfirm.id) return;

    try {
      await api.dataTransfer.delete(deleteConfirm.id);
      await loadItems();
      setDeleteConfirm({ show: false, id: null });
    } catch (err) {
      console.error('Error deleting transfer check:', err);
      alert('Failed to delete record. Please try again.');
    }
  };

  const toggleStatus = async (item: DataTransferCheck) => {
    if (!item.transferId) return;
    const nextStatus: Record<Status, Status> = {
      'Not Started': 'Pending',
      'Pending': 'Completed',
      'Completed': 'Not Started'
    };
    const updated = { ...item, status: nextStatus[item.status], isCompleted: nextStatus[item.status] === 'Completed' };
    try {
      await api.dataTransfer.update(item.transferId, updated);
      await loadItems();
    } catch (err) {
      console.error('Error updating status:', err);
    }
  };

  const filtered = items.filter(i => {
    const matchesSearch = i.moduleName.toLowerCase().includes(search.toLowerCase()) ||
      i.tableNameDesktop.toLowerCase().includes(search.toLowerCase()) ||
      i.tableNameWeb.toLowerCase().includes(search.toLowerCase());
    const matchesStatus = statusFilter === 'All' || i.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const exportCSV = () => {
    const headers = ['Module', 'Sub Module', 'Desktop Table', 'Web Table', 'Status'];
    const rows = filtered.map(i => [i.moduleName, i.subModuleName, i.tableNameDesktop, i.tableNameWeb, i.status]);
    const csvContent = [headers, ...rows].map(e => e.join(",")).join("\n");
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `transfer_checks_${projectId}.csv`);
    link.click();
  };

  const getStatusColor = (status: Status) => {
    switch (status) {
      case 'Completed': return 'bg-emerald-500 text-white';
      case 'Pending': return 'bg-orange-500 text-white';
      default: return 'bg-slate-300 dark:bg-zinc-700 text-slate-700 dark:text-zinc-300';
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="flex flex-col items-center gap-4">
          <Loader2 className="w-8 h-8 animate-spin text-blue-600" />
          <p className="text-slate-500 dark:text-zinc-400">Loading transfer checks...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <Link to={`/projects/${projectId}`} className="p-2 -ml-2 text-slate-400 hover:text-blue-600 rounded-lg transition-colors">
            <ArrowLeft size={24} />
          </Link>
          <div>
            <h1 className="text-3xl font-bold">Data Transfer Checks</h1>
            <p className="text-slate-500 dark:text-zinc-400 mt-1">Checklist for table migration tracking.</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={exportCSV}
            className="inline-flex items-center gap-2 px-4 py-2.5 bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-lg font-medium text-slate-700 dark:text-white hover:bg-slate-50 dark:hover:bg-zinc-800 transition-all shadow-sm"
          >
            <Download size={18} />
            Export
          </button>
          <button
            onClick={() => { setEditingItem(null); setShowModal(true); }}
            className="inline-flex items-center gap-2 px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-all shadow-sm"
          >
            <Plus size={18} />
            Add Row
          </button>
        </div>
      </div>

      <div className="flex flex-col md:flex-row gap-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
          <input
            type="text"
            placeholder="Search tables or modules..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-xl outline-none focus:ring-2 focus:ring-blue-500/20 transition-all shadow-sm"
          />
        </div>
        <div className="flex items-center gap-2">
          <Filter className="text-slate-400" size={18} />
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value as any)}
            className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 text-sm rounded-xl px-4 py-2.5 outline-none focus:ring-2 focus:ring-blue-500/20 shadow-sm"
          >
            <option value="All">All Statuses</option>
            <option value="Not Started">Not Started</option>
            <option value="Pending">Pending</option>
            <option value="Completed">Completed</option>
          </select>
        </div>
      </div>

      <div className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-2xl shadow-sm overflow-hidden">
        <div className="overflow-x-auto notion-scrollbar">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 dark:bg-zinc-800/50 border-b border-slate-200 dark:border-zinc-800">
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-zinc-400 w-12 text-center">Done</th>
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-zinc-400">Module</th>
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-zinc-400">Sub Module</th>
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-zinc-400">Condition</th>
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-zinc-400">Desktop Table</th>
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-zinc-400">Web Table</th>
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-zinc-400">Status</th>
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-zinc-400 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-zinc-800">
              {filtered.map(item => (
                <tr key={item.transferId} className="hover:bg-slate-50/50 dark:hover:bg-zinc-800/30 transition-colors group">
                  <td className="px-6 py-4 text-center">
                    <button
                      onClick={() => toggleStatus(item)}
                      className={`w-6 h-6 rounded-md border flex items-center justify-center transition-all ${item.status === 'Completed'
                        ? 'bg-emerald-500 border-emerald-500 text-white'
                        : 'border-slate-300 dark:border-zinc-700 bg-transparent text-transparent hover:border-blue-500'
                        }`}
                    >
                      <Check size={14} strokeWidth={4} />
                    </button>
                  </td>
                  <td className="px-6 py-4">
                    <span className="font-semibold text-sm">{item.moduleName}</span>
                  </td>
                  <td className="px-6 py-4">
                    <span className="text-sm text-slate-600 dark:text-zinc-400">{item.subModuleName}</span>
                  </td>
                  <td className="px-6 py-4">
                    <span className="text-sm text-slate-500 dark:text-zinc-500 italic max-w-[200px] truncate block" title={item.condition}>{item.condition || '-'}</span>
                  </td>
                  <td className="px-6 py-4">
                    <code className="px-2 py-1 bg-slate-100 dark:bg-zinc-800 rounded text-xs font-mono text-slate-700 dark:text-zinc-300">{item.tableNameDesktop}</code>
                  </td>
                  <td className="px-6 py-4">
                    <code className="px-2 py-1 bg-blue-50 dark:bg-blue-900/20 rounded text-xs font-mono text-blue-700 dark:text-blue-400">{item.tableNameWeb}</code>
                  </td>
                  <td className="px-6 py-4">
                    <button
                      onClick={() => toggleStatus(item)}
                      className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider transition-colors ${getStatusColor(item.status)}`}
                    >
                      {item.status}
                    </button>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <div className="flex items-center justify-end gap-1">
                      <button
                        onClick={() => {
                          setEditingItem(item);
                          setSelectedModule(item.moduleName);
                          setShowModal(true);
                        }}
                        className="p-1.5 text-slate-400 hover:text-blue-600 dark:hover:text-blue-400 transition-colors"
                      >
                        <Edit3 size={16} />
                      </button>
                      <button
                        onClick={() => item.transferId && handleDelete(item.transferId)}
                        className="p-1.5 text-slate-400 hover:text-red-500 transition-colors"
                      >
                        <Trash2 size={16} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
              {filtered.length === 0 && (
                <tr>
                  <td colSpan={7} className="px-6 py-12 text-center text-slate-400 italic">
                    No records found for this project.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Modal */}
      {showModal && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm">
          <div className="bg-white dark:bg-zinc-900 w-full max-w-lg rounded-2xl shadow-2xl overflow-hidden">
            <div className="p-6 border-b border-slate-100 dark:border-zinc-800 flex items-center justify-between">
              <h2 className="text-xl font-bold">{editingItem ? 'Edit Row' : 'Add New Row'}</h2>
              <button onClick={() => setShowModal(false)} className="text-slate-400 hover:text-slate-600 dark:hover:text-white">
                <XIcon size={20} />
              </button>
            </div>
            <form onSubmit={handleSave}>
              <div className="p-6 space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-semibold mb-1.5">Module Name</label>
                    <select
                      name="moduleName"
                      value={selectedModule}
                      onChange={(e) => setSelectedModule(e.target.value)}
                      required
                      className="w-full px-4 py-2 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                    >
                      <option value="">Select Module</option>
                      {uniqueModules.map(m => (
                        <option key={m} value={m}>{m}</option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-semibold mb-1.5">Sub Module</label>
                    <select
                      name="subModuleName"
                      defaultValue={editingItem?.subModuleName}
                      required
                      disabled={!selectedModule}
                      className="w-full px-4 py-2 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl focus:ring-2 focus:ring-blue-500 outline-none disabled:opacity-50"
                    >
                      <option value="">Select Sub-Module</option>
                      {availableSubModules.map(sm => (
                        <option key={sm} value={sm}>{sm}</option>
                      ))}
                    </select>
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-semibold mb-1.5">Condition</label>
                  <input name="condition" defaultValue={editingItem?.condition || ''} className="w-full px-4 py-2 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl outline-none focus:ring-2 focus:ring-blue-500" placeholder="Optional filter condition..." />
                </div>
                <div>
                  <label className="block text-sm font-semibold mb-1.5">Table Name (Desktop)</label>
                  <select
                    name="tableNameDesktop"
                    defaultValue={editingItem?.tableNameDesktop || ""}
                    required
                    disabled={!selectedModule}
                    className="w-full px-4 py-2 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl outline-none focus:ring-2 focus:ring-blue-500 font-mono disabled:opacity-50"
                  >
                    <option value="" disabled hidden>Select Desktop Table</option>
                    {distinctDesktopTables.map(t => (
                      <option key={t} value={t}>{t}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-semibold mb-1.5">Table Name (Web)</label>
                  <select
                    name="tableNameWeb"
                    defaultValue={editingItem?.tableNameWeb || ""}
                    required
                    disabled={!selectedModule}
                    className="w-full px-4 py-2 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl outline-none focus:ring-2 focus:ring-blue-500 font-mono disabled:opacity-50"
                  >
                    <option value="" disabled hidden>Select Web Table</option>
                    {distinctWebTables.map(t => (
                      <option key={t} value={t}>{t}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-semibold mb-1.5">Initial Status</label>
                  <select name="status" defaultValue={editingItem?.status || 'Not Started'} className="w-full px-4 py-2 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl outline-none focus:ring-2 focus:ring-blue-500">
                    <option value="Not Started">Not Started</option>
                    <option value="Pending">Pending</option>
                    <option value="Completed">Completed</option>
                  </select>
                </div>
              </div>
              <div className="p-6 bg-slate-50 dark:bg-zinc-800/50 flex gap-3">
                <button type="button" onClick={() => setShowModal(false)} className="flex-1 py-2.5 bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-700 rounded-xl font-medium">Cancel</button>
                {editingItem && (
                  <button type="button" onClick={handleSaveAs} disabled={saving} className="flex-1 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-bold shadow-lg shadow-emerald-500/20 disabled:opacity-50">
                    {saving ? 'Saving...' : 'Save As New'}
                  </button>
                )}
                <button type="submit" disabled={saving} className="flex-1 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-bold shadow-lg shadow-blue-500/20 disabled:opacity-50">
                  {saving ? 'Saving...' : (editingItem ? 'Update Record' : 'Save Record')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {deleteConfirm.show && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-zinc-900 rounded-2xl shadow-2xl max-w-md w-full border border-slate-200 dark:border-zinc-800">
            <div className="p-6">
              <div className="flex items-center gap-4 mb-4">
                <div className="w-12 h-12 rounded-full bg-red-100 dark:bg-red-900/30 flex items-center justify-center">
                  <Trash2 size={24} className="text-red-600 dark:text-red-400" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white">Delete Record</h3>
                  <p className="text-sm text-slate-500 dark:text-zinc-400">This action cannot be undone</p>
                </div>
              </div>
              <p className="text-slate-600 dark:text-zinc-300 mb-6">
                Are you sure you want to delete this record? All data associated with this record will be permanently removed.
              </p>
              <div className="flex gap-3">
                <button
                  onClick={() => setDeleteConfirm({ show: false, id: null })}
                  className="flex-1 py-2.5 px-4 bg-slate-100 dark:bg-zinc-800 hover:bg-slate-200 dark:hover:bg-zinc-700 rounded-xl font-medium transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={confirmDelete}
                  className="flex-1 py-2.5 px-4 bg-red-600 hover:bg-red-700 text-white rounded-xl font-bold shadow-lg shadow-red-500/20 transition-all"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

const XIcon = ({ size }: { size: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18" /><path d="m6 6 12 12" /></svg>
);

export default TransferChecks;
