
import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { api } from '../services/api';
import { VerificationRecord, VerificationStatus, ModuleMaster } from '../types';
import { Plus, Search, Filter, Trash2, Edit3, Download, Check, Code, MessageSquare, Info, ShieldCheck, Loader2, Copy, ArrowLeft } from 'lucide-react';

const VerificationList: React.FC = () => {
  const { projectId: projectIdStr } = useParams<{ projectId: string }>();
  const projectId = projectIdStr ? parseInt(projectIdStr, 10) : 0;

  const [items, setItems] = useState<VerificationRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [saving, setSaving] = useState(false);
  const [editingItem, setEditingItem] = useState<VerificationRecord | null>(null);
  const [selectedStatus, setSelectedStatus] = useState<VerificationStatus>('Pending');
  const [deleteConfirm, setDeleteConfirm] = useState<{ show: boolean; id: number | null }>({ show: false, id: null });

  // Module Master State
  const [moduleMasters, setModuleMasters] = useState<ModuleMaster[]>([]);
  const [selectedModule, setSelectedModule] = useState<string>('');

  const loadItems = async () => {
    if (!projectId) return;
    try {
      const [data, modules] = await Promise.all([
        api.verification.getByProject(projectId),
        api.moduleMaster.getAll()
      ]);
      setItems(data);
      setModuleMasters(modules);
    } catch (err) {
      console.error('Error loading data:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadItems();
  }, [projectId]);

  useEffect(() => {
    if (editingItem) {
      setSelectedModule(editingItem.moduleName);
    } else {
      setSelectedModule('');
    }
  }, [editingItem]);

  const uniqueModules = Array.from(new Set(moduleMasters.map(m => m.moduleName)));
  const availableSubModules = moduleMasters
    .filter(m => m.moduleName === selectedModule)
    .map(m => m.subModuleName);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    try {
      const form = e.target as HTMLFormElement;
      const formData = new FormData(form);

      const itemData: VerificationRecord = {
        verificationId: editingItem?.verificationId, // Undefined for new items
        projectId: projectId,
        moduleName: formData.get('moduleName') as string,
        subModuleName: formData.get('subModuleName') as string,
        fieldName: formData.get('fieldName') as string,
        description: formData.get('description') as string,
        status: selectedStatus,
        sqlQuery: formData.get('sqlQuery') as string,
        expectedResult: formData.get('expectedResult') as string || '',
        actualResult: formData.get('actualResult') as string || '',
        isVerified: selectedStatus === 'Correct',
        comments: editingItem?.comments || ''
      };

      if (editingItem?.verificationId) {
        await api.verification.update(editingItem.verificationId, itemData);
      } else {
        await api.verification.create(itemData);
      }

      await loadItems();
      setShowModal(false);
      setEditingItem(null);
      setSelectedStatus('Pending');
    } catch (err) {
      console.error('Error saving verification:', err);
      alert('Failed to save verification. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const handleSaveAs = async (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    setSaving(true);
    try {
      const button = e.currentTarget;
      const form = button.closest('form');
      if (!form) throw new Error('Form not found');

      const formData = new FormData(form);

      const newItem: VerificationRecord = {
        // ID generated by backend
        projectId: projectId,
        moduleName: formData.get('moduleName') as string,
        subModuleName: formData.get('subModuleName') as string,
        fieldName: formData.get('fieldName') as string,
        description: formData.get('description') as string,
        status: selectedStatus,
        sqlQuery: formData.get('sqlQuery') as string,
        expectedResult: formData.get('expectedResult') as string || '',
        actualResult: formData.get('actualResult') as string || '',
        isVerified: selectedStatus === 'Correct',
        comments: ''
      };

      await api.verification.create(newItem);
      await loadItems();
      setShowModal(false);
      setEditingItem(null);
      setSelectedStatus('Pending');
    } catch (err) {
      console.error('Error saving as new verification:', err);
      alert('Failed to save as new record. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = (id: number) => {
    setDeleteConfirm({ show: true, id });
  };

  const confirmDelete = async () => {
    if (!deleteConfirm.id) return;

    try {
      await api.verification.delete(deleteConfirm.id);
      await loadItems();
      setDeleteConfirm({ show: false, id: null });
    } catch (err) {
      console.error('Error deleting verification:', err);
      alert('Failed to delete record. Please try again.');
    }
  };

  const getStatusBadge = (status: VerificationStatus) => {
    switch (status) {
      case 'Correct': return 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400';
      case 'Incorrect': return 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400';
      case 'Pending': return 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400';
      case 'Re-verify': return 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400';
      default: return 'bg-slate-100 text-slate-700 dark:bg-zinc-800 dark:text-zinc-400';
    }
  };

  const filtered = items.filter(i =>
    i.moduleName.toLowerCase().includes(search.toLowerCase()) ||
    i.fieldName.toLowerCase().includes(search.toLowerCase())
  );

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="flex flex-col items-center gap-4">
          <Loader2 className="w-8 h-8 animate-spin text-blue-600" />
          <p className="text-slate-500 dark:text-zinc-400">Loading verifications...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <Link to={`/projects/${projectId}`} className="p-2 -ml-2 text-slate-400 hover:text-blue-600 rounded-lg transition-colors">
            <ArrowLeft size={24} />
          </Link>
          <div>
            <h1 className="text-3xl font-bold">Verification List</h1>
            <p className="text-slate-500 dark:text-zinc-400 mt-1">Audit and verify field-level logic accuracy.</p>
          </div>
        </div>
        <button
          onClick={() => {
            setEditingItem(null);
            setSelectedStatus('Pending');
            setShowModal(true);
          }}
          className="inline-flex items-center gap-2 px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium shadow-sm transition-all"
        >
          <Plus size={18} />
          New Verification
        </button>
      </div>

      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
        <input
          type="text"
          placeholder="Filter by field, module or description..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="w-full pl-10 pr-4 py-2.5 bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-xl outline-none shadow-sm focus:ring-2 focus:ring-blue-500/20"
        />
      </div>

      <div className="grid grid-cols-1 gap-4">
        {filtered.map(item => (
          <div key={item.verificationId} className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-all">
            <div className="p-6">
              <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${getStatusBadge(item.status)}`}>
                      {item.status}
                    </span>
                    <span className="text-xs font-semibold text-slate-400 uppercase tracking-widest">{item.moduleName} / {item.subModuleName}</span>
                  </div>
                  <h3 className="text-lg font-bold">{item.fieldName}</h3>
                  <p className="text-sm text-slate-600 dark:text-zinc-400 mt-1">{item.description}</p>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <button onClick={() => {
                    setEditingItem(item);
                    setSelectedModule(item.moduleName);
                    setSelectedStatus(item.status);
                    setShowModal(true);
                  }} className="p-2 text-slate-400 hover:text-blue-500 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded-lg transition-colors">
                    <Edit3 size={18} />
                  </button>
                  <button className="p-2 text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-colors">
                    <Trash2 size={18} />
                  </button>
                </div>
              </div>

              {item.sqlQuery && (
                <div className="mt-4 bg-slate-50 dark:bg-zinc-800/50 rounded-xl p-4 border border-slate-100 dark:border-zinc-800">
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2 text-slate-500 dark:text-zinc-400">
                      <Code size={14} />
                      <span className="text-xs font-bold uppercase">SQL Reference</span>
                    </div>
                    <CopyButton text={item.sqlQuery} />
                  </div>
                  <pre className="text-xs font-mono text-slate-700 dark:text-zinc-300 overflow-x-auto notion-scrollbar whitespace-pre-wrap">
                    {item.sqlQuery}
                  </pre>
                </div>
              )}

              <div className="mt-4 pt-4 border-t border-slate-100 dark:border-zinc-800 flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <div className="flex items-center gap-1.5 text-xs text-slate-500 dark:text-zinc-400">
                    <MessageSquare size={14} />
                    {item.comments ? 'Has Comments' : 'No Comments'}
                  </div>
                  <div className="flex items-center gap-1.5 text-xs text-slate-500 dark:text-zinc-400">
                    <Check size={14} className={item.isVerified ? 'text-emerald-500' : 'text-slate-300'} />
                    {item.isVerified ? 'Verified' : 'Unverified'}
                  </div>
                </div>
                <button className="text-xs font-bold text-blue-600 hover:text-blue-700">Add Comment</button>
              </div>
            </div>
          </div>
        ))}
        {filtered.length === 0 && (
          <div className="py-20 text-center bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-2xl border-dashed">
            <ShieldCheck size={48} className="mx-auto text-slate-200 mb-4" />
            <h3 className="text-lg font-bold">No verification items yet</h3>
            <p className="text-slate-500 dark:text-zinc-400">Create tests to ensure data integrity.</p>
          </div>
        )}
      </div>

      {/* Modal */}
      {showModal && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm overflow-y-auto">
          <div className="bg-white dark:bg-zinc-900 w-full max-w-2xl rounded-2xl shadow-2xl overflow-hidden my-auto">
            <div className="p-6 border-b border-slate-100 dark:border-zinc-800 flex items-center justify-between">
              <h2 className="text-xl font-bold">{editingItem ? 'Edit Verification' : 'New Verification Item'}</h2>
              <button onClick={() => setShowModal(false)} className="text-slate-400 hover:text-slate-600 dark:hover:text-white">
                <XIcon size={20} />
              </button>
            </div>
            <form onSubmit={handleSave} className="p-6 space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold mb-1.5">Module</label>
                  <select
                    name="moduleName"
                    value={selectedModule}
                    onChange={(e) => setSelectedModule(e.target.value)}
                    required
                    className="w-full px-4 py-2 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                  >
                    <option value="">Select Module</option>
                    {uniqueModules.map(m => (
                      <option key={m} value={m}>{m}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-semibold mb-1.5">Sub Module</label>
                  <select
                    name="subModuleName"
                    defaultValue={editingItem?.subModuleName}
                    required
                    disabled={!selectedModule}
                    className="w-full px-4 py-2 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl focus:ring-2 focus:ring-blue-500 outline-none disabled:opacity-50"
                  >
                    <option value="">Select Sub-Module</option>
                    {availableSubModules.map(sm => (
                      <option key={sm} value={sm}>{sm}</option>
                    ))}
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1.5">Field/Logic Name</label>
                <input name="fieldName" defaultValue={editingItem?.fieldName} required className="w-full px-4 py-2 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl focus:ring-2 focus:ring-blue-500 outline-none" placeholder="e.g. Calculated Tax Total" />
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1.5">Description/Notes</label>
                <textarea name="description" defaultValue={editingItem?.description} className="w-full px-4 py-2 bg-slate-50 dark:bg-zinc-800 border-none rounded-xl focus:ring-2 focus:ring-blue-500 outline-none min-h-[80px]" />
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1.5">SQL Query (Reference)</label>
                <textarea name="sqlQuery" defaultValue={editingItem?.sqlQuery} className="w-full px-4 py-3 bg-slate-900 text-emerald-400 font-mono text-xs border-none rounded-xl focus:ring-2 focus:ring-emerald-500 outline-none min-h-[120px]" placeholder="SELECT * FROM Leads WHERE..." />
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1.5 text-slate-500">Status</label>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                  {(['Pending', 'Correct', 'Incorrect', 'Re-verify'] as VerificationStatus[]).map(st => (
                    <button
                      key={st}
                      type="button"
                      onClick={() => setSelectedStatus(st)}
                      className={`flex items-center justify-center py-2 rounded-xl text-xs font-bold cursor-pointer transition-all border ${selectedStatus === st
                        ? 'bg-blue-600 text-white border-blue-600'
                        : 'bg-slate-50 dark:bg-zinc-800 border-transparent hover:border-slate-300 dark:hover:border-zinc-700'
                        }`}
                    >
                      {st}
                    </button>
                  ))}
                </div>
              </div>
              <div className="pt-4 flex gap-3">
                <button type="button" onClick={() => setShowModal(false)} className="flex-1 py-3 bg-slate-100 dark:bg-zinc-800 rounded-xl font-bold">Cancel</button>
                {editingItem && (
                  <button type="button" onClick={handleSaveAs} disabled={saving} className="flex-1 py-3 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-bold shadow-lg shadow-emerald-500/20 transition-all disabled:opacity-50">
                    {saving ? 'Saving...' : 'Save As New'}
                  </button>
                )}
                <button type="submit" disabled={saving} className="flex-1 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-bold shadow-lg shadow-blue-500/20 transition-all disabled:opacity-50">
                  {saving ? 'Saving...' : (editingItem ? 'Update Verification' : 'Save Verification')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {deleteConfirm.show && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-zinc-900 rounded-2xl shadow-2xl max-w-md w-full border border-slate-200 dark:border-zinc-800">
            <div className="p-6">
              <div className="flex items-center gap-4 mb-4">
                <div className="w-12 h-12 rounded-full bg-red-100 dark:bg-red-900/30 flex items-center justify-center">
                  <Trash2 size={24} className="text-red-600 dark:text-red-400" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white">Delete Verification</h3>
                  <p className="text-sm text-slate-500 dark:text-zinc-400">This action cannot be undone</p>
                </div>
              </div>
              <p className="text-slate-600 dark:text-zinc-300 mb-6">
                Are you sure you want to delete this verification record? All data will be permanently removed.
              </p>
              <div className="flex gap-3">
                <button
                  onClick={() => setDeleteConfirm({ show: false, id: null })}
                  className="flex-1 py-2.5 px-4 bg-slate-100 dark:bg-zinc-800 hover:bg-slate-200 dark:hover:bg-zinc-700 rounded-xl font-medium transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={confirmDelete}
                  className="flex-1 py-2.5 px-4 bg-red-600 hover:bg-red-700 text-white rounded-xl font-bold shadow-lg shadow-red-500/20 transition-all"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

const XIcon = ({ size }: { size: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18" /><path d="m6 6 12 12" /></svg>
);

const CopyButton = ({ text }: { text: string }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  return (
    <button
      onClick={handleCopy}
      className="flex items-center gap-1.5 px-2 py-1 hover:bg-slate-200 dark:hover:bg-zinc-700 rounded-md transition-colors text-xs font-medium text-slate-500 hover:text-slate-700 dark:text-zinc-400 dark:hover:text-zinc-200"
      title="Copy SQL query"
    >
      {copied ? <Check size={12} className="text-emerald-500" /> : <Copy size={12} />}
      <span>{copied ? 'Copied!' : 'Copy'}</span>
    </button>
  );
};

export default VerificationList;
